### ISSUE TITLE
Programmatically trigger checkPos()

### ISSUE THREAD

**Issue by silvestreh** [silvestreh/onScreen#14]
Make it so checkPos() can be triggered manually.

**Comment by jenrique7** [comment]
Hey! Any update on this? Cheers

**Comment by silvestreh** [comment]
Not yet. I've been swamped with work and I really couldn't get my hands on the plugin in a while. I'm making some other small changes, but this is something I want to do.

You can check [isOnScreen](https://github.com/moagrius/isOnScreen) in the meantime.

**Comment by jenrique7** [comment]
Thanks!
