### ISSUE TITLE
Touch move support

### ISSUE THREAD

**Issue by billcolumbia** [silvestreh/onScreen#15]
I'm currently hacking on this now and trying to add support for ` .on({'touchmove' ` so that `doIn()` and other methods can be fired while scrolling on a touch device, instead of after the user stops scrolling. Were you thinking about implementing anything like this in the future? Thanks for a sweet tool, nonetheless :+1:

**Comment by silvestreh** [comment]
It's been… well, years. But I'm closing this issue as the new OnScreen is completely different and, as far as I could test (I only own one Android device) it works as intended.

**Comment by billcolumbia** [comment]
I was never able to get it working consistently back then. It seems it was added to both iOS Safari and Android browsers though 👍  thanks for the follow up!
