### ISSUE TITLE
Is there a way to Programmatically make a div offScreen and trigger "doOut"?

### ISSUE THREAD

**Issue by 1manStartup** [silvestreh/onScreen#18]
For example lets say I have a div that the plugin says is onScreen (example: div#main) which itself contains a list of items.

I notice in two instances... for example if I cover the div#main with another div making div#main "offScreen" and if I replace div#main with another div via backbonejs or jquery .show, it does not trigger "offScreen" state or "doOut".

So my question is if we can programmatically give a div ".offScreen" screen state and thus triggering "doOut".

It would be a nice feature to have, also thanks for this solid library.

**Comment by silvestreh** [comment]
I'm closing this issue as there's a new version of OnScreen with a completely different codebase. If I understand correctly, the new version will handle mutations to the DOM and taking care of things.
