### ISSUE TITLE
No bower version available.

### ISSUE THREAD

**Issue by jeff-blaisdell** [silvestreh/onScreen#19]
Bower does not have any versions available for this repository.

Running a bower info onScreen produces the following:
```
{
  name: 'onScreen',
  description: 'A jQuery plugin that does stuff when the matched elements are visible (as inside the viewport).',
  main: 'jquery.onscreen.js',
  keywords: [
    'jquery',
    'onscreen',
    'screen'
  ],
  authors: [
    'Silvestre Herrera'
  ],
  dependencies: {
    jquery: '*'
  },
  license: 'MIT',
  homepage: 'https://github.com/silvestreh/onScreen',
  ignore: [
    '**/.*'
  ]
}

No versions available.
```

I believe the issue is that you need to create a 0.1.0 tag in your git repository for bower to pull.

See http://stackoverflow.com/questions/19456091/bower-register-new-version

**Comment by silvestreh** [comment]
Hugest of delays on answering, I know. I'm rewriting the plugin and I'll publish it on NPM. Sorry for the inconvenience. Cheers!
