### ISSUE TITLE
Different tolerance for doIn and doOut

### ISSUE THREAD

**Issue by kwn** [silvestreh/onScreen#21]
Hi,

I'd like to differ the tollerance. I'd like to animate elements after passing some pixels (eg tolleranceIn: 250), and toggle class right after going outside the viewport (tolerace : 0)

Are you interested in PR? It will brake the API compatibility. "Tolerance" option will be replaced with toleranceIn and toleranceOut.

**Comment by metalgigio** [comment]
it would be also nice if tollerance was based on percentage of viewport instead of pixel. Because 50px could be a big part of the screen on a mobile phone but not so much on a desktop.
Sorry for my english :)

**Comment by Tooa** [comment]
I like both suggestions. With "in" and "out" tolerance one could also introduce an "entered" and "left" event that uses the two properties.

**Comment by silvestreh** [comment]
@Tooa those events are already implemented.

```javascript
var os = new OnScreen();

os.on('enter', '.someElement', function () {});
os.on('leave', '.someElement', function () {});
```

The tricky feature here would be different tolerance as I would need a way to determine wether you're scrolling up or down.

The other feature, the one about percentages, would be nice to have. I guess I would do something like…

```javascript
var os = new OnScreen({
    tolerance: '10%'
});
```

Using a number (instead of a string) would default to pixels so I don't break anyone's implementation.

**Comment by Tooa** [comment]
> those events are already implemented.

No, I mean something like described here [1] with `enter` and `entered`. 

[1] http://imakewebthings.com/waypoints/shortcuts/inview/

**Comment by silvestreh** [comment]
I see… well, in that case, the tolerance should only apply to `enter` and `entered` would trigger once the entire element is inside the viewport.

The problem, I believe, is that it might get confusing when an element is larger than the viewport and the `entered` event would never trigger.

**Comment by kwn** [comment]
I hope you're all well guys :) Closing the issue for now 😄
