### ISSUE TITLE
Ajax help

### ISSUE THREAD

**Issue by proov** [silvestreh/onScreen#23]
Hello :)

I've been using this script on different projets, i found it very usefull !

However i never used it with ajax loaded content... Any help to "watch" some divs which were loaded after the script init ? (they all have the same class ".reveal")

Many thanks :)

**Comment by silvestreh** [comment]
Not using the jquery plugin, no. You should probably need to re-run .onScreen() once the new nodes are appended to the DOM. I'm rewriting onScreen as an independent library (no jQuery dependency) and this problem is solved in the new version.

**Comment by proov** [comment]
woah!! i can't wait ! :) @silvestreh
