### ISSUE TITLE
onScreen doIn / doOut on init

### ISSUE THREAD

**Issue by proov** [silvestreh/onScreen#24]
Hello,

is there a way to trigger ```doIn``` function on init ? E.g : i have a gallery with multiples items, i'd like to animate these items when I init onScreen, and then, on scroll with the usual way :)

I think onScreen triggers only on scroll ? and not at init ?

Thanks :)

**Comment by silvestreh** [comment]
I'm closing this issue as there's a new version of OnScreen with a completely different codebase.
