### ISSUE TITLE
Can't remove event listener

### ISSUE THREAD

**Issue by dmazz55** [silvestreh/onScreen#26]
I have $(target).onScreen('remove'); call at the end of my doIn method - but the doIn gets called every time the element is on screen (I'm trying to just get it to fire the first time)

**Comment by silvestreh** [comment]
The event listener is attached to the window. It should be something like $(window).onScreen('remove');

**Comment by dmazz55** [comment]
So I have to remove it for all elements I've attached it to? I can't just remove it for one?

**Comment by dmazz55** [comment]
For anyone else that also wishes to disable the onScreen event after the first onScreen and finds that the remove option is not usable since you must remove the listener from all elements...

I simple added a class inside the doIn function to the element after my logic then check for the existing of that class at the beginning of the doIn function to prevent it from running again. This allows my other elements to still be able to use the onScreen without worrying about anything firing twice.

**Comment by dmazz55** [comment]
Here's a code snippet to demonstrate what I mentioned above 

![](http://i.imgur.com/MCNG7wm.jpg)
