### ISSUE TITLE
trigger doIn() only once per element

### ISSUE THREAD

**Issue by oozrafa** [silvestreh/onScreen#29]
Is there any way to remove onScreen from a specific element?
For example, my page is divided into sections and they all have the same class 'log_entered_viewport'. What I want is that only the first time they enter the viewport that onScreen will be triggered and I will log the event. If the users scrolls up and down the page and the particular section enters the viewport, then I only want it to be triggered once.

**Comment by oozrafa** [comment]
That was quick :) Solved it by adding a 'logged' class to the element and then checking for the class.
In other words, it's like the 'toggleClass' option, except that the class is removed.

doIn: function() {
	   		
	   		$e = $(this);
			
			if ( !$e.hasClass('logged') ){
			
				// -- code to log that the element has entered the viewport
			        
                                // add the class the mark that the element has been logged
				$e.addClass('logged');
			
			}
			
	   }

**Comment by silvestreh** [comment]
heh, I was going to suggest something along those lines
