### ISSUE TITLE
To gain a real position, i've to know all my ancestors

### ISSUE THREAD

**Issue by ifanjuang** [silvestreh/onScreen#30]
Thank you for this wonderfull plugin, I've had to add those lines inside checkPos function to retrieve the correct position relative to container, given that my elements are inside relatively positioned divs which are descendants of the scrolled Container.

Please correct me if i've mistaken on something,
```javascript
var $elAncestor = $el.offsetParent();
var i = 0;
while ((i < 5) && ($elAncestor[0] !== $container[0])){
  i++;
  var pos = $elAncestor.position();
  elTop += pos.top;
  elLeft += pos.left;
  $elAncestor= $elAncestor.offsetParent();
 }
```

**Comment by silvestreh** [comment]
While I'm not following what you're trying to accomplish, your code looks like valid javascript. `elTop` and `elLeft` look like global variables from here, but I'm sure you omitted the piece of code where you declare them using `var`.

I'm sorry I'm not of much help, but I didn't understand what you were trying to do :smile:

**Comment by sunyatasattva** [comment]
This issue title is extremely philosophical.
