### ISSUE TITLE
Where is onScreen static template?

### ISSUE THREAD

**Issue by onrea** [silvestreh/onScreen#31]
Hey there

formerly, onScreen was a theme; Where is it now? I'm using it on a production site; I wanted to know is there any update for it?!

![on screen img](https://cloud.githubusercontent.com/assets/6428449/13721654/86c0c37e-e842-11e5-8a17-0101aae2ed41.png)

**Comment by silvestreh** [comment]
onScreen was never a theme. It's a jQuery plugin. I'm planning on rewriting as an independent library (that means no jQuery dependency)

**Comment by onrea** [comment]
Ah, I found it! I mean this template: https://github.com/silvestreh/onScreen/tree/gh-pages

**Comment by silvestreh** [comment]
oh, that static site with demos. feel free to do whatever you want with it. :smile:
