### ISSUE TITLE
Uncaught TypeError: 'caller',

### ISSUE THREAD

**Issue by polikin** [silvestreh/onScreen#32]
I tried onScreen with Browserify, but I get this error.

Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

Code
```
let onScreen = require('../vendors/jquery.onscreen');

$('.speakers').onScreen({
            container: window,
            direction: 'vertical',
            doIn: function() {
             // Do something to the matched elements as they come in
            },
            doOut: function() {
             // Do something to the matched elements as they get off scren
            },
            tolerance: 0,
            throttle: 50,
            toggleClass: 'onScreen',
            lazyAttr: null,
            lazyPlaceholder: 'someImage.jpg',
            debug: false
        });
```

**Comment by silvestreh** [comment]
Yeah, this would be the throttle method. I'm in the process of rewriting this as a stand-alone library with no requirements.

**Comment by silvestreh** [comment]
I'm closing this issue as there's a new version of OnScreen with a completely different codebase.
