### ISSUE TITLE
ENOTFOUND Package onScreen not found

### ISSUE THREAD

**Issue by Mageking** [silvestreh/onScreen#37]
Hi,

We are getting this when we run bower install. Any idea why?

**Comment by prosellen** [comment]
I had the same problem too with an older project that used bower.
onScreen seems to have moved from jQuery to VanillaJS and from bower to npm as a package manager .

The good news is, that the old version can still be found in the "old-jquery" branch. So if you - like me - need the jQuery/bower version you can install it with
`bower install -s https://github.com/silvestreh/onScreen.git#old-jquery`
and/or update you bower.json to
`"onScreen": "https://github.com/silvestreh/onScreen.git#old-jquery"`

Hope this helps.

**Comment by silvestreh** [comment]
@Mageking: Just like @prosellen mentioned, I moved OnScreen from Bower to NPM and, for now at least, I plan to maintain only one package manager.
