### ISSUE TITLE
bug: enter called multiple times for the same element

### ISSUE THREAD

**Issue by Montrazul** [silvestreh/onScreen#40]
Hello. Im using the latest version (1.2.0) and wanted to use `OnScreen` on my canvas elements which are containing charts from `chart.js`. When i just use this code:

```javascript
os.on("enter", "canvas", function(element) {
    console.log("canvas enter: " + $(element).attr("id"));
});			
os.on("leave", "canvas", function(element) {
   console.log("canvas leave: " + $(element).attr("id"));
});
```

It is working correctly, the ouput is:

```
canvas enter: evaluation_combined_canvas_0
canvas leave: evaluation_combined_canvas_0
canvas enter: evaluation_combined_canvas_1
```

When i now add the `Chart.js` part:

```javascript
os.on("enter", "canvas", function(element) {
    console.log("canvas enter: " + $(element).attr("id"));
    var config = getConfigCombined($(element).attr("id"));
    var context = $(element);
    var combined = new Chart(context, config);
});			
os.on("leave", "canvas", function(element) {
   console.log("canvas leave: " + $(element).attr("id"));
});
```
The output is:

```
24 canvas enter: evaluation_combined_canvas_0
canvas enter: evaluation_combined_canvas_1
canvas enter: evaluation_combined_canvas_0
canvas enter: evaluation_combined_canvas_1
canvas enter: evaluation_combined_canvas_0
canvas enter: evaluation_combined_canvas_1
canvas enter: evaluation_combined_canvas_0
[…]
```

The "enter" now is called on every scroll.

**Comment by Montrazul** [comment]
Im not sure if this is an Issue with `OnScreen`. Could also be an issue with `Chart.js` or even `Canvas` itself.

**Comment by Montrazul** [comment]
Yes i do that intentionally. I have a list of round about 100 charts and the data needed for creating the charts are stored in the data attribute of the parent div of the canvas. It is ok even if it costs some milliseconds of the performance.

The problem is that on every scroll the "enter" is getting triggered.

**Comment by Montrazul** [comment]
I created a [https://jsfiddle.net/ov2wz2kb/1/](jsFiddle) to demonstrate whats happening

**Comment by Montrazul** [comment]
Until now i use a workaround. I store a `data-init="false"` in my `canvas` tag and i check this boolean in the `enter` event. If it is false i create the chart and set it to true. But as i said. Maybe it is an issue.

**Comment by silvestreh** [comment]
I just updated your fiddle, [check it out](https://jsfiddle.net/ov2wz2kb/2/). The problem, it seems, is that you were re-instantiating your charts over and over again.

**Comment by silvestreh** [comment]
Also, check the DOM of your original fiddle. A new `iframe` is created for every pixel you scroll. This will account for more than a few milliseconds in the long run 😄 .

**Comment by Montrazul** [comment]
But now you just took out the chart creation out of the `enter` event. That is not what i want. If i do it like you posted it users would have to wait over 20 secons with a frozen ui (as i said i have over 100 charts in one list all displaying different data). That was the reason why i only wanted to load a chart, if it is visible in the view bounds of the browser.

So when there is no chart in the canvas, only the canvas itself, the `enter` and `leave` events are called only when you enter or leave a canvas.

When you add the chart code the `enter` event is getting triggered on every scroll.

**Comment by silvestreh** [comment]
Ok… I guess I misinterpreted the original scenario. Have you taken a look into [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)?

**Comment by Montrazul** [comment]
No but i will have a look at it. I guess i figured out the problem. `Chart.js` is replacing the original canvas with a new canvas. That is the reason why `enter` is getting called over and over again.

So going with a boolean flag like I did [here](https://jsfiddle.net/ov2wz2kb/3/) is ok. Thank you

**Comment by silvestreh** [comment]
Awesome. I'm sorry I wasn't of much help, I'm really not familiar with Char.js.

Web Workers are worth taking a look at. They're great for these kind of problems where you need to do heavy tasks outside of the main thread so as to not block the event loop. I believe they're supported in IE10 and above. Chrome, Firefox, Safari, and Opera, all support Web Workers.
