### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by Jaxwood** [silvestreh/onScreen#41]
If I do a :
`bower install onScreen`

I get the follow error message:
> ENOTFOUND Package onScreen not found

In my bower.json I have the following dependency:

> "onScreen": "*"

**Comment by silvestreh** [comment]
The package is no longer available on Bower, only NPM. If you still want the old jQuery plugin you can put this into your `bower.json`

```json
"onScreen": "https://github.com/silvestreh/onScreen.git#old-jquery"
```

If you want to use the new, with no-dependencies, library just run:

```shell
npm install --save onscreen
```
