### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by dodozhang21** [silvestreh/onScreen#43]
I've been using this script via my bower dependency but since the upgrade, I can no longer do that. Can you add your final dist file into the repo so bower can pull it down?

**Comment by silvestreh** [comment]
If you're still using Bower I would advice to pull OnScreen directly from the repo. Add this to your `bower.json`:

```
"onScreen": "https://github.com/silvestreh/onScreen.git#old-jquery"
```

or install it using

```
bower install -s https://github.com/silvestreh/onScreen.git#old-jquery
```

As you can probably tell, this will pull the old jQuery plugin and not the latest release. For the time being, I'm only publishing to NPM to avoid the hassle of maintaining multiple package managers and have no plans to start publishing to other sources.

**Comment by dodozhang21** [comment]
I see. I can actually also pull it down via npm. Your dist folder has two versions: umd & es6. Do both of these require another lib to work or doe sit work out of the box like the old jQuery one? I need the `check` functionality which I believe isn't available in the old version.

**Comment by silvestreh** [comment]
You should use the UMD version to be safe as it should work with IE9+. The ES6 version uses JavaScript features not available in all browsers.

**Comment by fede91it** [comment]
Why don't support a standard bower install?

**Comment by silvestreh** [comment]
@fede91it I'll quote myself from a few comments up 😄 

> I'm only publishing to NPM to avoid the hassle of maintaining multiple package managers

**Comment by fede91it** [comment]
Why the new version doesn't support bower and we must use old version?

**Comment by silvestreh** [comment]
You don't have. Just remove the `#old-jquery` hash that points to the branch with the old version.

```shell
bower install -s https://github.com/silvestreh/onScreen.git
```

But do note that you'll be getting the ES6 version, you'll have to run it though a transpiler like Babel.

**Comment by fede91it** [comment]
I don't have the /dist folder when I install via bower...

Ok I can compile by mylself, but we you don't provide a dist package also for bower and not only for npm?

**Comment by silvestreh** [comment]
Because the `dist/` directory holds transpiled code which has no place in the source repository. What bower does, basically, is clone the repo.

**Comment by fede91it** [comment]
Ok indeed

**Comment by silvestreh** [comment]
@fede91it and everyone else that uses bower… you can pull the latest, compiled, version from unpkg. Just add this to your `bower.json` file:

```json
dependencies: {
    "onscreen": "https://unpkg.com/onscreen/dist/on-screen.umd.min.js"
}
```

Or simply run this form a terminal:

```shell
bower install --save onscreen=https://unpkg.com/onscreen/dist/on-screen.umd.min.js 
```

I'll put this info on the README for everyone to see 😄

**Comment by silvestreh** [comment]
It's on the README file! 😁
