### ISSUE TITLE
Example of destory

### ISSUE THREAD

**Issue by Mr-Alexander** [silvestreh/onScreen#48]
It would be great to have an example of how to use the os.destroy() functionality, it is not clear from your documentation.

**Comment by silvestreh** [comment]
It's pretty straight forward. In all snippets `os` is the OnScreen instance:

```javascript
const os = new OnScreen();

os.on('.selector', () => {});
os.destroy();
```

**Comment by Mr-Alexander** [comment]
I was referring to the following scenario:

1. You assign the on enter for a set of elements, ".selector"
2. When a specific element from the set has entered the viewport, perform the "doIt" function
3. Remove the "enter" event for the element from the specific element from the set, only for the element that has finished loading, not the entire ".selector"

**Comment by silvestreh** [comment]
The implementation of that scenario is up to the developer. I would suggest having some kind of flag that you check while running the "doIt" function…

```javascript
const os = new OnScreen();

os.on('enter', '.selector', (element) => {
    if (!element.entered) {
        // Write whatever you want to do with the `element`

        // Set the flag so this code block won't run next time the `element` enters the viewport
        element.entered = true;
    }
});
```

In the above snippet `element` is an instance of `DOMElement`. I added a new property to the `element` object to track if it entered the viewport before. If you don't want to add properties to `element` you could add a new attribute instead:

```javascript
os.on('enter', '.selector', (element) => {
    if (!element.getAttribute('entered')) {
        // Write whatever you want to do with the `element`

        // Set the flag so this code block won't run next time the `element` enters the viewport
        element.setAttribute('entered', true);
    }
});
```

In your scenario, `.destroy()` isn't needed at all. What `.destroy()` does is removing the event listener from the `window` (or `HTMLElement` if you're using a different container) object. Once you remove the event listener you can add again it using `.attach()`.
