### ISSUE TITLE
off() Method throws an error if trackedElements only has 'enter' or 'leave'

### ISSUE THREAD

**Issue by kyleshevlin** [silvestreh/onScreen#53]
In my application, I only have need for using the enter hook. The `off` method attempts to create callback arrays for enter and leave hooks, without any safeguard for the scenario where one doesn't have any callbacks for that hook. Thus it throws this error:

```
Uncaught TypeError: Cannot convert undefined or null to object
```

A potential solution would be something like this:

```js
function off(event, selector, handler) {
    const enterCallbacks = Object.keys(this.trackedElements[selector].enter || {});
    const leaveCallbacks = Object.keys(this.trackedElements[selector].leave || {});
```

This way `Object.keys()` returns an empty array instead of an error if one of these hooks isn't used. There might be a more fundamental way to approach this, such as ensuring the trackedElements[selector] has this property defined in the case one isn't provided, but this is a possible solution.

I have forked the repo and can make the change, but I can't get to it until, at the earliest, tomorrow. If it's faster or easier for you or someone else to do it, be my guest.

**Comment by silvestreh** [comment]
Good catch! Thanks! I'll take a look ASAP 😄

**Comment by kyleshevlin** [comment]
Out of curiosity, is there any chance of this getting released as a patch version?

**Comment by silvestreh** [comment]
I thought I had released it. I'll check again when I get home. Hang on there 😅

**Comment by kyleshevlin** [comment]
No worries, if you did maybe it just wasn't tagged here on the repo. The last release here on the repo is 1.1.3 over a year ago.

**Comment by kyleshevlin** [comment]
I just upgraded the package and got 1.3.1, so I'm guessing the tags just aren't getting updated here on the repo. Thanks for your work.

**Comment by silvestreh** [comment]
Yeah! That's probably it. I'll make sure to create the tags in the future!
