### ISSUE TITLE
Input: Improving scrolling performance

### ISSUE THREAD

**Issue by ekesto** [silvestreh/onScreen#59]
First of all, thanks for this great tool, it is working great!

Today I've been analysing a project with the "Audits" tool of Chrome Dev Tools, and it suggests to implement "Passive Event Listeners" to improve scrolling performance:
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

Might be something worth looking into?

Best wishes!

**Comment by silvestreh** [comment]
Yeah, definitely. Looks like it's [safe to use](http://caniuse.com/#feat=passive-event-listener).
