### ISSUE TITLE
Events fire on page load, not on scroll

### ISSUE THREAD

**Issue by jaredrutledge** [silvestreh/onScreen#60]
I just loaded the js from unpkg - 
```
<script type="text/javascript" src="https://unpkg.com/onscreen/dist/on-screen.umd.min.js"></script>
```

and then used the following code:

```
var os = new OnScreen();

os.on('enter', '#elementId', (element, event) => {
    element.style.backgroundColor = 'red';
});
```

The div immediately turns red on page load if it's visible in the viewport. If the element is not in the viewport, scrolling to it effects no changes.

**Comment by jaredrutledge** [comment]
After some research, it appears that overflow-x: hidden on body and html breaks javascript scrolling listeners, as referenced [here](https://stackoverflow.com/questions/17665080/overflow-x-hidden-is-breaking-jquery-scroll-event). I'm using bodymovin for some svg animation and it had that bit of css in there to make the animations work.

**Comment by silvestreh** [comment]
Then you might want to set the container to be the `body`.
