### ISSUE TITLE
Ionic 3 Can't get this to work

### ISSUE THREAD

**Issue by shukrihd** [silvestreh/onScreen#66]
Hi I need some help. I have installed the package with 'npm i onscreen --save'. How do implement this to a page? I have imported this on my page

import { OnScreen } from 'onscreen';

ngAfterViewInit() {
    const os = new OnScreen({
        tolerance: 0,
        debounce: 100,
        container: window
    });

    console.log(os);
  }

I'm getting error 

__WEBPACK_IMPORTED_MODULE_4_onscreen__.OnScreen is not a constructor

How do I actually use this?

**Comment by silvestreh** [comment]
You're destructuring the import. It's:

```
import OnScreen from 'onscreen';
```

So when you `import { OnScreen }` you're basically getting `undefined`.
