### ISSUE TITLE
Option to not use debounced scrolling

### ISSUE THREAD

**Issue by gavin310** [silvestreh/onScreen#74]
_This is a feature request, not an issue._

I understand why debounced scrolling is used, but sometimes you want events triggered even while scrolling. Sorry, but I'm not good with git, so what I did was create a `handleScroll` function to be called instead of `debouncedScroll`. If the `debounced` option === `false` then handleScroll calls `eventHandler` immediately. If `debounced` is not `false` then it does a `return debouncedScroll.call(this);`.

I think having the option to not use debounced scrolling would be a useful addition to this great library.

```
	/**
	 * Determines whether scroll event should be fired immediately or debounced
	 *
	 * @return {void}
	 */
	function handleScroll() {
		var _this = this;

		var debounce = this.options.debounce;

		if (debounce === false) {
			return function () {
				eventHandler(_this.trackedElements, _this.options);
			}
		}
		else {
			return debouncedScroll.call(this);
		}
	}
```

**Comment by silvestreh** [comment]
or you can set `options.debounce` to `0` and there will be no debouncing.

**Comment by gavin310** [comment]
@silvestreh I tried that, but the `enter` event still fired only after scrolling had stopped.

**Comment by gavin310** [comment]
@silvestreh https://jsfiddle.net/yvsfwtod/ In this jsfiddle `debounce` is set to `0` and it doesn't remove debouncing for me. Is debouncing removed for you in this example?

**Comment by silvestreh** [comment]
Alright! I just published 1.4.0 😄

**Comment by gavin310** [comment]
Wow that was fast! Thanks! Your method is much simpler/better than mine ;)

**Comment by gavin310** [comment]
Oops, sorry, I forgot to mention that I also needed to add `this._scroll();` at the end of the `on` function. The `enter` event wasn't being triggered if `debounce` was set to false and the element was already in the viewport on page load.

```
function on(event, selector, callback) {
  ...
  this._scroll();
}
```

**Comment by silvestreh** [comment]
If I understand correctly, you can use the static method `OnScreen.check` when the page loads.
